id: P006871
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24788
  title: ངའི་ཆུར་བ་སུས་ཁྱེར་སོང་།
  author: ''
  volumes:
    b5ed3c5514164c5e8209fde8beea6f59:
      image_group_id: I1KG24790
      title: ''
      volume_number: 1
      total_pages: 159
